name: Rebuild

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Architecture'
        default: 'amd64 armhf'
        required: true
      dist:
        description: 'Distribution'
        default: 'stretch buster buster-staging'
        required: true

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Rebuild packages list
        uses: menucha-de/actions/rebuild@v1
        with:
          arch: ${{ github.event.inputs.arch }}
          dist: ${{ github.event.inputs.dist }}
          token: ${{ secrets.ACTIONS }}
